compartment_id: ocid1.tenancy.oc1..aaaaaaaauf3wvaslx5qnkkqi7sgwep4h2pcsyu7ozv4qrruwex5q4yotyseq
vcn_id: ocid1.vcn.oc1.eu-stockholm-1.amaaaaaaw45bjiqac37pefbrq7exrwppgxleeugqmgr7fwclrya3jocyyefa
security_list_id: ocid1.securitylist.oc1.eu-stockholm-1.aaaaaaaa24qmorzfhs2ipfsjpmoe6tzbs6f4dwj45yi6jwjrtszjjz6md4cq
