words = [
    "ansible",
    "btrbk",
    "btrfs",
    "caddy",
    "cloudflare",
    "copyparty",
    "cron",
    "forgejo",
    "fqcn",
    "headscale",
    "nas",
    "ntfy",
    "tailscale",
    "ufw",
]
