---
vps:
  children:
    backup:
      hosts:
        kvasir:
          ansible_host: kvasir.andersens.xyz
    vpn:
      hosts:
        forsete:
          ansible_host: 45.133.117.53
    srv:
      hosts:
        forsete:
          ansible_host: forsete.andersens.xyz
        høner:
          ansible_host: 172.245.197.82
    wsl:
      hosts:
        thor:
    oci:
      hosts:
        trym:
          ansible_host: 129.151.199.180
        surtur:
          ansible_host: 79.76.33.54
        suttung:
          ansible_host: 79.76.61.110
local:
  children:
    nas:
      hosts:
        mimer:
          ansible_host: 10.10.10.10
