---
# plugin: yaml
vps:
  children:
    backup:
      hosts:
        kvasir:
    vpn:
      hosts:
        forsete:
    srv:
      hosts:
        høner:
          ansible_host: 172.245.197.82

local:
  children:
    nas:
      hosts:
        mimer:
          ansible_host: 10.10.10.10
    gateway:
      hosts:
        heimdall:
          ansible_host: 10.10.0.1
    workstation:
      hosts:
        thor:
        tyr:
