vps:
  backup:
    kvasir:
      ansible_host: 198.23.177.75
  vpn:
    forsete
      ansible_host: 45.133.117.53
  srv:
    høner:
      ansible_host: 172.245.197.82

local:
  nas:
    mimer:
      ansible_host: 10.10.10.10
  gateway:
    heimdall:
      ansible_host: 10.10.0.1
  workstation:
    thor:
    laptop:
      tyr:
