---
- name: Common setup
  hosts: vps
  roles:
    - harden

- name: Set up headscale orchestrator
  hosts: vpn
  roles:
    - headscale

- name: Set up server nodes
  hosts: srv
  roles:
    - docker
