user:
  name: norseghost
  uid: 1000
  group: users
  shell: /usr/bin/zsh
  email: martin.andreas.andersen@gmail.com
  pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG3mZSaRskxRMZmjYmAVMljWAWyR5an9bTrxtBGPSKK4

dns:
  domain: andersens.xyz
acme:
  account_key_src: "/etc/ssl/acme/account.key"
  email: "{{ user.email }}"
  directory: "https://acme-v02.api.letsencrypt.org/directory"
