user:
  name: norseghost
  uid: 1000
  group: users
  shell: /usr/bin/zsh
  email: martin.andreas.andersen@gmail.com
  pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG3mZSaRskxRMZmjYmAVMljWAWyR5an9bTrxtBGPSKK4

dns:
  domain: andersens.xyz
acme:
  account_key_src: "/etc/ssl/acme/account.key"
  email: "{{ user.email }}"
  directory: "https://acme-v02.api.letsencrypt.org/directory"
  client_dir: /opt/acme.sh
  renew_cron_hour: 3
  renew_cron_minute: 17
headscale_domain: "{{ dns.domain }}"
headscale_subdomain: bifrost
headscale_fqdn: "{{ headscale_subdomain }}.{{ headscale_domain }}"
headscale_url: "https://{{ headscale_fqdn }}"
