---
- name: Ensure dependencies for btrbk
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true

- name: Install btrbk from package
  ansible.builtin.apt:
    name: btrbk
    state: present
  register: btrbk_installed
  failed_when: false

- name: Set up btrbk subvolumes

- name: Set up btrbk configuration
