---
- name: Ensure dependencies for btrbk
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Install btrbk from package
  apt:
    name: btrbk
    state: present
  register: btrbk_installed
  failed_when: false

- name: Set up btrbk subvolumes

- name: Set up btrbk configuration
