---
- block:
  - name: Make sure host and path are set
    ansible.builtin.assert:
      that:
        - btrbk_remote != ""
        - btrbk_remote_path != ""
      fail_msg:  "You need to set a remote host and path for remote backup"

  - name: Make sure SSH identity is set
    ansible.builtin.assert:
      that:
        - btrbk_ssh_private_key != ""
        - btrbk_ssh_public_key != ""
      fail_msg: "You need to set a != {}
    fail_msg: "You need to specify subvolumes to back up"

- name: Include UnRAID tasks
  include_task: unraid.yml
  when: "'Unraid' in ansible_facts.kernel"

- name: Include other distribution tasks
  include_task: "{{ ansible_facts.ansible_distribution | lower }}.yml"
  when: "'Unraid' not in ansible_facts.kernel"

- name: Create btrbk SSH directory
  ansible.builtin.file:
    path: "{{ btrbk_ssh_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Copy btrbk ssh identity file
  ansible.builtin.copy:
    content: "{{ btrbk_ssh_private_key }}"
    dest: "{{ btrbk_ssh_dir }}/{{ btrbk_ssh_identity }}"
    owner: root
    group: root
    mode: "0600"

- name: Generate btrbk.conf
  ansible.builtin.template:
    dest: "{{ btrbk_conf_dir }}/btrbk.conf"
    owner: "99"
    group: "100"
    mode: "0644"
    src: btrbk.conf.j2

- name: Inspect btrfs filesystem
  community.general.btrfs_info:
  register: btrbk_btrfs_data

- name: Debug btrfs filesystem data
  ansible.builtin.debug:
    var: btrbk_btrfs_data

- name: Process Btrfs data for btrbk targets
  set_fact:
    btrbk_configs: >-
      {%- set results = [] -%}
      {%- for fs in btrbk_btrfs_data.filesystems -%}
        {%- for target_path in btrbk_volumes -%}
          {# Find the ID of the subvolume actually mounted at our target #}
          {%- set root_match = fs.subvolumes | selectattr('mountpoints', 'contains', target_path) | first | default(none) -%}

          {%- if root_match -%}
            {# filter:
               1. parent must match root ID
               2. path must NOT have more than one level of nesting (regex)
               3. ignore hidden paths (starting with .)
            #}
            {%- set children = fs.subvolumes
              | selectattr('parent', 'equalto', root_match.id)
              | map(attribute='path')
              | reject('match', '^/[^/]+/[^/]+')
              | select('match', '^/(?!\\.).*')
              | map('regex_replace', '^/', '')
              | list
            -%}

            {%- if children | length > 0 -%}
              {%- set _ = results.append({
                'mount': target_path,
                'device': fs.devices,
                'subvolumes': children,
                'uuid': fs.uuid
              }) -%}
            {%- endif -%}
          {%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ results }}

- name: Debug btrfs filesystem data
  ansible.builtin.debug:
    var: btrbk_configs

- name: Dry run planned backups
  ansible.builtin.command:
    cmd: "{{ btrbk_command }} dryrun"
  check_mode: false
  register: unraid_btrbk_output
  changed_when: false # Prevents the task from reporting "changed" every time

- name: Display btrbk dry run results
  ansible.builtin.debug:
    var: unraid_btrbk_output.stdout_lines
