- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "99"
    group: "100"
    mode: "0750"
  loop:
    - "{{ btrbk_install_dir }}/bin"
    - "{{ btrbk_install_dir }}/config"
    - "{{ btrbk_install_dir }}/logs"

- name: Download btrbk
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/digint/btrbk/master/btrbk"
    dest: "{{ btrbk_install_dir }}/bin/btrbk"
    mode: "0755"

- name: Generate btrbk.conf
  ansible.builtin.template:
    dest: "{{ btrbk_install_dir }}/config/btrbk.conf"
    owner: "99"
    group: "100"
    mode: "0644"
    src: btrbk.conf.j2

- name: Create btrbk SSH directory
  ansible.builtin.file:
    path: "{{ btrbk_install_dir }}/ssh"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Install btrbk SSH private key
  ansible.builtin.copy:
    content: "{{ btrbk_ssh_private_key }}"
    dest: "{{ btrbk_ssh_identity }}"
    owner: root
    group: root
    mode: "0600"

- name: Install btrbk SSH public key
  ansible.builtin.copy:
    content: "{{ btrbk_ssh_public_key }}"
    dest: "{{ btrbk_ssh_identity }}.pub"
    owner: root
    group: root
    mode: "0644"
- name: Ensure snapshot directories exist on disk roots
  ansible.builtin.file:
    # This regex extracts /mnt/disk4 or /mnt/sysdata from the path
    path: "{{ item.value | regex_replace('^(/mnt/[^/]+).*', '\\1') }}/.snapshots"
    state: directory
    owner: "99"
    group: "100"
    mode: "0750"
  with_dict: "{{ btrbk_volumes }}"

# - name: Ensure remote btrbk target subvolumes exist
#   ansible.builtin.command: >
#     ssh -i {{ btrbk_ssh_identity }}
#     -o StrictHostKeyChecking=accept-new
#     root@{{ btrbk_remote }}
#     "btrfs subvolume create {{ btrbk_remote_path }}/{{ item.key }} || true"
#   loop: "{{ btrbk_volumes | dict2items }}"
#   changed_when: false

- name: Ensure btrbk cron job is installed via go
  ansible.builtin.lineinfile:
    path: /boot/config/go
    insertafter: EOF
    line: |
      # btrbk cron
      echo "{{ cron_schedule }} {{ btrbk_command }} run" > /etc/cron/btrbk
    state: present
- name: Install btrbk cron job (runtime)
  ansible.builtin.copy:
    dest: /etc/cron.d/btrbk
    content: |
      {{ cron_schedule }} {{ btrbk_command }} run
    owner: root
    group: root
    mode: "0644"
- name: dry run planned backups
  ansible.builtin.command:
    cmd: "{{ btrbk_command }} dryrun"
  check_mode: false
  register: btrbk_output
  changed_when: false # Prevents the task from reporting "changed" every time

- name: Display btrbk dry run results
  ansible.builtin.debug:
    var: btrbk_output.stdout_lines
