---
- name: Set up API store
  when:
    - headscale_api_key is not defined
  block:
    - name: Generate headscale API key
      ansible.builtin.command:
        cmd: headscale apikey create
      register: headscale_api_key_cmd
      changed_when: true

    - name: Capture headscale API key
      ansible.builtin.set_fact:
        _headscale_new_api_key: "{{ headscale_api_key_cmd.stdout | trim }}"
      no_log: true

    - name: Store headscale API key in vault
      ansible.builtin.include_role:
        name: vault_kv_set
      vars:
        vault_file: group_vars/all/secrets.yml
        vault_key: headscale_api_key
        vault_value: "{{ _headscale_new_api_key }}"
