---
- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ headscale_user }}"
    group: "{{ headscale_group }}"
    mode: "0750"
  loop:
    - "{{ headscale_lib_dir }}"
    - "{{ headscale_run_dir }}"
    - "{{ headscale_config_dir }}"
    - "{{ headscale_le_cache_dir}}"

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Check if headscale binary exists
  ansible.builtin.stat:
    path: /usr/bin/headscale
  register: headscale_bin

- name: Configure Headscale ACL for bidirectional subnet routing
  ansible.builtin.template:
    src: acl.json.j2
    dest: "{{ headscale_config_dir }}/acl.json"
    owner: "{{ headscale_user }}"
    group: "{{ headscale_group }}"
    mode: '0644'
  notify: Restart headscale
  when: headscale_bin.stat.exists

- name: Install config.yaml
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ headscale_config_dir }}/config.yaml"
    owner: "{{ headscale_user }}"
    group: "{{ headscale_group }}"
    mode: "0640"
  notify: Restart headscale
  when: headscale_bin.stat.exists
