- name: Install headscale deb
  when: headscale_install_needed
  ansible.builtin.apt:
    deb: "/tmp/headscale_{{ headscale_resolved_version }}.deb"
    state: present

- name: Remove downloaded deb
  when: headscale_install_needed
  ansible.builtin.file:
    path: "/tmp/headscale_{{ headscale_resolved_version }}.deb"
    state: absent
