---
- name: ++ detect headscale version ++
  ansible.builtin.import_tasks: detect.yml
- name: ++ dowload headscale if required ++
  ansible.builtin.import_tasks: download.yml
- name: ++ install headscale if required ++
  ansible.builtin.import_tasks: install.yml
- name: ++ set up headscale networking ++
  ansible.builtin.import_tasks: network.yml
- name: ++ configure headscale ++
  ansible.builtin.import_tasks: config.yml
- name: ++ enable headscale service ++
  ansible.builtin.import_tasks: service.yml
- name: ++ generate headscale api key ++
  ansible.builtin.import_tasks: apikey.yml
- name: ++ set up users ++
  ansible.builtin.import_tasks: users.yml
