---
- name: Ensure DNS record for {{ headscale_fqdn }}
  community.general.cloudflare_dns:
    zone: "{{ headscale.domain }}"
    record: "{{ headscale.subdomain }}"
    type: A
    value: "{{ ipv4_addr }}"
    api_token: "{{ cloudflare.api_token }}"

- name: Create headscale certificate directory
  ansible.builtin.file:
    path: "{{ headscale.acme.cert_dir }}"
    state: directory
    mode: "0750"

- name: Generate private key for letsencrypt certificate generation
  community.crypto.openssl_privatekey:
    path: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.key"
    size: 4096

- name: Create CSR for headscale
  community.crypto.openssl_csr:
    path: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.csr"
    privatekey_path: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.key"
    common_name: "{{ headscale_fqdn }}"

- name: Start ACME order (DNS-01 challenge)
  community.crypto.acme_certificate:
    terms_agreed: true
    account_key_src: "{{ acme.account_key_src }}"
    acme_directory: "{{ headscale.acme.directory }}"
    acme_version: 2
    account_email: "{{ headscale.acme.email }}"
    challenge: dns-01
    csr: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.csr"
    remaining_days: 9999
    dest: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.pem"
  register: acme_start

- name: Create Cloudflare TXT record for ACME DNS-01 challenge
  community.general.cloudflare_dns:
    zone: "{{ headscale.domain }}"
    record: "_acme-challenge.{{ headscale_fqdn }}"
    type: TXT
    value: "{{ acme_start.challenge_data[headscale_fqdn]['dns-01'].resource_value }}"
    ttl: 60
    api_token: "{{ cloudflare.api_token }}"
    solo: true
  register: cf_txt

- name: Wait for TXT record to propagate
  pause:
    seconds: 30

- name: Finalize ACME order (issue certificate)
  community.crypto.acme_certificate:
    terms_agreed: true
    acme_directory: "{{ headscale.acme.directory }}"
    acme_version: 2
    account_email: "{{ headscale.acme.email}}"
    account_key_src: "{{ acme.account_key_src }}"
    challenge: dns-01
    data: "{{ acme_start }}"
    csr: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.csr"
    fullchain_dest: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.crt"
    chain_dest: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}-chain.crt"
    dest: "{{ headscale.acme.cert_dir }}/{{ headscale_fqdn }}.pem"
    remaining_days: 30
  register: acme_finalize
