---
- name: Ensure DNS record for {{ headscale_fqdn }}
  community.general.cloudflare_dns:
    zone: "{{ headscale.domain }}"
    record: "{{ headscale.subdomain }}"
    type: A
    value: "{{ ipv4_addr }}"
    api_token: "{{ cloudflare.api_token }}"

- name: Ensure Caddy conf.d directory exists
  ansible.builtin.file:
    path: /etc/caddy/conf.d
    state: directory
    owner: caddy
    group: caddy
    mode: '0755'

- name: Deploy Caddy service configuration
  ansible.builtin.template:
    src: headscale.caddy.j2
    dest: "/etc/caddy/conf.d/headscale.caddy"
    owner: caddy
    group: caddy
    mode: '0644'
  notify: "reload caddy"
