---
- name: Ensure Headscale users exist
  ansible.builtin.command:
    cmd: "headscale user create {{ item }}"
  register: headscale_user_creation
  # Headscale returns an error if the user exists; we ignore that specific error
  failed_when:
    - headscale_user_creation.rc != 0
    - "'UNIQUE constraint failed' not in headscale_user_creation.stderr"
  changed_when:
    - headscale_user_creation.rc == 0
  loop: "{{ headscale_users }}"
