---
- name: Create group {{ user.group }}
  group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

- name: Create user {{ user.name }} and assign to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user.password }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    groups: sudo
    append: yes
  tags:
    - user

- name: Add SSH config directory for {{ user.name }}
  file:
    path: ~/.ssh
    mode: 0700
    state: directory
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - ssh

- name: Copy key files for ssh to {{ user.name }}
  copy:
    content: id_ed25519_admin
    # TODO: more custom keys, ssh agents, etc
    dest: ~/.ssh/id_ed25519
    mode: 0600
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - ssh

- name: Add SSH public key to {{ user.name }} authorised keys
  authorized_key:
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG3mZSaRskxRMZmjYmAVMljWAWyR5an9bTrxtBGPSKK4
    state: present
    user: "{{ user.name }}"
  tags:
    - ssh
