---
- name: Create user group {{ user.group }}
  ansible.builtin.group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

- name: Create user {{ user.name }}
  ansible.builtin.user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user_secrets.password }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    groups: sudo
    append: true
  tags:
    - user

- name: Add SSH config directory for {{ user.name }}
  ansible.builtin.file:
    path: ~/.ssh
    mode: "0700"
    state: directory
  become: true
  become_user: "{{ user.name }}"
  tags:
    - ssh

- name: Copy key files for ssh to {{ user.name }}
  ansible.builtin.copy:
    content: id_ed25519_admin
    # TODO: more custom keys, ssh agents, etc
    dest: ~/.ssh/id_ed25519
    mode: "0600"
  become: true
  become_user: "{{ user.name }}"
  tags:
    - ssh

- name: Add SSH public key to {{ user.name }}
  ansible.posix.authorized_key:
    key: "{{ user.pubkey }}"
    state: present
    user: "{{ user.name }}"
  tags:
    - ssh

- name: install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: allow ssh through ufw
  community.general.ufw:
    rule: allow
    port: 22

- name: Enable UFW
  community.general.ufw:
    state: enabled
